apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: alertas-reportes-ms
  name: alertas-reportes-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertas-reportes-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alertas-reportes-ms
    spec:
      containers:
      - image: us-east4-docker.pkg.dev/douremember-477701/douremember-registry/alertas-reportes-ms
        name: alertas-reportes-ms
        env:
        - name: PORT
          value: "3003"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: RESEND_API_KEY
          valueFrom:
            secretKeyRef:
              name: alertas-reportes-secrets
              key: resend_api_key 
        - name: EMAIL_FROM
          valueFrom:
            secretKeyRef:
              name: alertas-reportes-secrets
              key: email_from
        - name: EMAIL_FROM_ADDRESS
          valueFrom:
            secretKeyRef:
              name: alertas-reportes-secrets
              key: email_from_address
        resources:
          requests:
            cpu: "150m"
            memory: "384Mi"
          limits:
            cpu: "400m"
            memory: "768Mi"
status: {}
